### ISSUE TITLE
For musicians - change the order

### ISSUE THREAD

**Issue by jparedes123** [brooklyn-symphony-orchestra/bso#27]
This page should have the dues at the top, then bowings

Under dues, add a button to pay dues online that takes you to the Pay Dues page

Move the schedule and rehearsals content to a new page for "Rehearsals"

**Comment by jparedes123** [comment]
The order is now right, but is there a way to (a) remove the 'For Musicians' link from the drop down menu and instead have the main nav item that says 'For Musicians' point toward that page?

Also, do we have the rehearsals information for next season to put up? If not, I can reach out to Kate/Jill+Sarah.

**Comment by awkale** [comment]
I updated the menu and the rehearsals are populated.
https://bklyn-symphony.squarespace.com/rehearsals/
