### ISSUE TITLE
how to join - form changes

### ISSUE THREAD

**Issue by jparedes123** [brooklyn-symphony-orchestra/bso#36]
Change the CTA copy to "Submit"
Remove phone number from the form
Add a dropdown for the instrument
Ensure that the form is connected to mailchimp

**Comment by jparedes123** [comment]
Looks good. Two questions:
1. Should we add an 'Other' for the drop down just in case we get people interested who don't fit our list? 
2. I can't confirm the MailChimp aspect of this - has that been tested?

**Comment by awkale** [comment]
I can add other. Right now I'm doing a simple email to the membership manager. I thought it might be better to let them control the flow of information. Once we have someone, I can review having the form populate mailchimp directly.
