### ISSUE TITLE
Artistic Director and Assistant Conductor - nav

### ISSUE THREAD

**Issue by jparedes123** [brooklyn-symphony-orchestra/bso#37]
Add a page called Artistic Director and Assistant Conductor and move the content from the appropriate pages

**Comment by jparedes123** [comment]
Looks good. Do you think we should have separate pages for Nick and Felipe?

Or, should we call this page Artistic Leadership rather than their titles?

**Comment by jparedes123** [comment]
As discussed, keep it as a combined page and retitle the nav item to 'Artistic Leadership'

**Comment by awkale** [comment]
navigation has been updated to Artistic Leadership
